name: Simple ML Pipeline

on:
  push:
    branches: [main]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Create MLflow directory
        run: mkdir -p mlruns


      - name: Train the model
        env:
          MLFLOW_TRACKING_URI: file:./mlruns
        run: python src/train.py