name: Simple ML Pipeline

on:
  push:
    branches: [main]      # runs every time you push to main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest   # GitHub gives you a free Linux machine

    steps:

      - name: Get the code
        uses: actions/checkout@v4
        # downloads your repo onto the GitHub machine

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
        # same as you running this on your laptop

      - name: Train the model
        run: python src/train.py
        # if this crashes, the pipeline stops and shows red X

      - name: Build Docker image
        run: docker build -t sentiment-api .
        # proves the app can be packaged successfully